language: c++
dist: trusty
sudo: false
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libssl-dev
      - libssh2-1-dev
cache:
  directories:
    - ${HOME}/dependencies
env:
  global:
    - PROCS=2
  matrix:
    - LIBUV_VERSION=1.20.0
install:
  - if [ ! -d "${HOME}/dependencies/libuv-${LIBUV_VERSION}" ]; then
      wget -q --no-check-certificate http://dist.libuv.org/dist/v${LIBUV_VERSION}/libuv-v${LIBUV_VERSION}.tar.gz;
      tar xzf libuv-v${LIBUV_VERSION}.tar.gz;
      (
        cd libuv-v${LIBUV_VERSION};
        sh autogen.sh;
        ./configure --prefix=${HOME}/dependencies/libuv-${LIBUV_VERSION};
        make -j${PROCS} install;
      )
    else echo "Using Cached libuv v${LIBUV_VERSION}. Dependency does not need to be re-compiled";
    fi
before_script:
  - EXTRA_CXX_FLAGS=
  - EXTRA_C_FLAGS=
  - if [ "$CXX" == "clang++" ]; then
      EXTRA_CXX_FLAGS="-Wno-unknown-warning-option -Wno-gnu-folding-constant -Wno-sign-compare";
      EXTRA_C_FLAGS="-Wno-unknown-warning-option";
    fi
  - (
      mkdir build;
      cd build;
      CFLAGS="${EXTRA_C_FLAGS}" CXXFLAGS="${EXTRA_CXX_FLAGS}" cmake -DCMAKE_BUILD_TYPE=Release -DLIBUV_ROOT_DIR=${HOME}/dependencies/libuv-${LIBUV_VERSION}/ -DCASS_BUILD_STATIC=On -DCASS_BUILD_EXAMPLES=On -DCASS_BUILD_UNIT_TESTS=On ..
    )
script:
  - make -C build -j${PROCS}
  - build/cassandra-unit-tests --gtest_filter="*SessionBase*"
  - if [ -f build/libcassandra_static.a ]; then
      declare -a FUNCTIONS MISSING_FUNCTIONS;
      FUNCTIONS=($(grep -Eoh '^cass_\s*(\w+)\s*\(' include/cassandra.h | awk -F '(' '{print $1}'));
      for function in "${FUNCTIONS[@]}"; do
        nm build/libcassandra_static.a | grep ${function} > /dev/null;
        if [ $? -ne 0 ]; then
          MISSING_DEFINITION+=("${function}");
        fi;
      done;
      if [ ! -z "${MISSING_DEFINITION}" ]; then
        printf "Function(s) have no definition:\n";
        for function in ${MISSING_DEFINITION[@]}; do
          printf "  ${function}\n";
        done;
        exit 1;
      fi;
    fi
